version: '3'
services: 
  mysql:
    container_name: mysql_server_5.6
    image: mysql/mysql-server:5.6
    ports:
      - 3306:3306
    networks: 
      - default
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_ROOT_HOST=%
    restart: always
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]