version: '3'
services: 
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    networks: 
      - default
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    restart: always
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]